name: Verify lib
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Test library
    runs-on: windows-latest
    env:
      CI: true
      FORCE_COLOR: 3
      NO_COLOR: false
      TERM: xterm-256color

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test:ci
